### ISSUE TITLE
[Integrate] As a user, I can see Trending list on Home page

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/jetpack-compose-crypto#14]
## Why

When the user launches the app, it will show the "Trending 🔥" section on the Home page.

## Acceptance Criteria

- Mapping the data from API response to display on UI:
![image](https://user-images.githubusercontent.com/6950766/178645724-783e2e83-33cd-4fc0-81cd-69ff808211b8.png)
  - If the field `price_change_percentage_24h_in_currency`:
    - Positive number: Use green color with arrow up `#10DC78`
    - Negative number: Use red color with arrow down `#F15950`
- Use [Coil](![image](https://user-images.githubusercontent.com/6950766/173727375-0b7197cd-232a-4339-af0c-5b2537b7e685.png)) to load the coin image
~~- Handle pagination when user scroll down to end of the list~~

## Design

N/A

## Resources

N/A

**Comment by luongvo** [comment]
> Handle pagination when user scroll down to end of the list

@hoangnguyen92dn Do you mean we should implement scroll down to load more? 🤔

**Comment by hoangnguyen92dn** [comment]
@luongvo Yup. It would be a challenge to handle pagination with Column in Compose 😄

**Comment by luongvo** [comment]
@hoangnguyen92dn I see what you mean but I think we should separate this AC into a new ticket as the integration part is quite big enough from this PR https://github.com/nimblehq/jetpack-compose-crypto/pull/31. You can create a new ticket and assign it to me 🧑‍🍳

**Comment by hoangnguyen92dn** [comment]
@luongvo That's fine. I will create anothet ticket for pagination. Thank you.

**Comment by hoangnguyen92dn** [comment]
@luongvo I updated the description to get rid of pagination on this ticket and created a new one https://github.com/nimblehq/jetpack-compose-crypto/issues/32 to handle that.
