### ISSUE TITLE
Setup CICD pipelines

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/jetpack-compose-crypto#2]
## Why

Add the CICD pipelines to execute the following workflow:
- Detekt > Android Lint > UnitTest > Danger (Refer: [review_pull_request.yml](https://github.com/nimblehq/android-templates/blob/develop/.cicdtemplate/.github/workflows/review_pull_request.yml))
- Deploy release build, allow to use debug build since we don't create keystore for release. (Refer: [deploy_staging_and_production_to_firebase_app_distribution.yml](https://github.com/nimblehq/android-templates/blob/develop/.cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml))

## Who Benefits?

Developers

**Comment by luongvo** [comment]
@hoangnguyen92dn should we close this?
