### ISSUE TITLE
[Chore] As a user, I can see the coin image fit circular and crop in center

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/jetpack-compose-crypto#33]
## Why

The coin images return from API in different styles (circular, square, transparent background, etc.), the coin images are displaying inconsistency on my coins and trending coins.

<img src="https://user-images.githubusercontent.com/6950766/189574226-5dae0a36-34a4-4ebb-876e-d11534299157.png" width=350 />

## Acceptance Criteria

- Display the coin image fit circular and crop in center
- Default background color if the background is transparent: `#f3f4fa`
- Horizontal list items display with the same size

![Image](https://user-images.githubusercontent.com/6950766/189573981-03f51445-c817-46a5-809e-4505bbb61e93.png)

## Design

https://www.figma.com/file/HioYp71LllKVy9qaiLauKn/Crypto-App-(Community)?node-id=3%3A181

## Resources

N/A

**Comment by luongvo** [comment]
@hoangnguyen92dn Sorry but I still don't see the issue, could you please clarify more with example 🤔 What I'm seeing is all the icons are in the same vertical lines 🤔
