### ISSUE TITLE
Missing Box Shadow in PortfolioCard 

### ISSUE THREAD

**Issue by wasim15185** [nimblehq/jetpack-compose-crypto#52]
## Missing Box-Shadow in PortfolioCard Composable

As per Figma Design The app missing Box-Show 

## Screen-Show is Below
 
<a href="https://imgur.com/5sSbwgX"><img src="https://i.imgur.com/5sSbwgX.jpg" title="source: imgur.com"  height="300px" width="150px" alt="box-showmissing-img" /></a>

**Comment by hoangnguyen92dn** [comment]
@wasim15185 Thank you for submitting the issue to our repo, and we appreciate your effort. We are aware of the problem, and addressed issue #22 

We will review your opening PR as soon as possible 🏃
