### ISSUE TITLE
[Modularization] Create UI test example for Detail screen

### ISSUE THREAD

**Issue by doannimble** [nimblehq/jetpack-compose-crypto#83]
## Why

It is a good time for us to get more experience with UI tests, especially when using `Compose`
## Acceptance Criteria

- UI test for `Home` screen, it is related to https://github.com/nimblehq/jetpack-compose-crypto/issues/74
- Create UI test for `Detail` Screen
- We can choose between Espresso or Roboelectric 

## Resources

https://developer.android.com/jetpack/compose/testing

**Comment by Wadeewee** [comment]
@doannimble, We have this [issue](https://github.com/nimblehq/jetpack-compose-crypto/issues/74) for the UI Test `HomeScreen`, So I think this issue can be created for UI Test `DetailScreen` 🙏

**Comment by doannimble** [comment]
Thanks for your info @Wadeewee , I will link it to this issue
